
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcazibqjhuwqbqxwlvgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjYXppYnFqaHV3cWJxeHdsdmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NjU2MjQsImV4cCI6MjA1NDM0MTYyNH0.9XD09Wh5sL9Ny9ehOvPj-uI4eJFiM0psvgd9zQMqZig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
